#!/usr/bin/python3

import json
import sys

json_str = ""

for line in sys.stdin:
  json_str += line

json_data = json.loads(json_str)

i = json_data[0]['value']

json_output = {
  "variant": "bool",
  "value": i % 2 == 0
}

print(json.dumps(json_output))
